[SAM_MODEL]
Model_Type              = "vit_b_histopathology"  # "vit_h": normal sam, vit_b_histopathology/vit_h_histopathology/vit_l_histopathology: Histopathology
pathosam_postprocess    = true   # <— set to true to run NMS+edge-filter on PathoSAM proposals
points_per_side         = 32
points_per_batch        = 256
pred_iou_thresh         = 0.86  #0.86
stability_score_thresh  = 0.92  #0.92
box_nms_thresh          = 0.1  # 0.02
min_mask_region_area    = 50   #80
max_mask_region_area    = 3600

[BASEMODEL]
Training_Stratgy    	= "AllCells"
Mask_Input		        = true

Use_Mask                = true            # whether to use any mask‐fusion at all
Mask_Fusion             = "concat"           # one of: "concat", "add", "film"
Use_Text_Mask           = false            # whether to use text‐mask

Backbone                = "uni_v2"       # or virchow2 / resnet18, conch_v1, uni_v1
LoRA                    = true            # whether to use LoRA
full_finetune           = false           # whether to fully finetune the backbone
Batch_Size              = 64

Unfreeze_last           = 0                # 0 = linear-probe, 2 = last-2 blocks, etc.
Input_Type              = "3_Channel"
Activation              = "Identity"
Model                   = "convnet"
Loss_Function           = "CrossEntropyLoss"
Precision               = "16-mixed"
Vis                     = [0]
Num_of_Worker           = 12
GPU_ID                  = [0]
Max_Epochs              = 30
Random_Seed             = 9374
 
[AUGMENTATION]
horizontalflip          = 0.5
randombrightnesscontrast= 0.2
Colour_Sigma            = 0.014
Colour_Mode             = 'uniform'

[CHECKPOINT]
logger_folder           = './lightning_logs/'
model_name              = "Classifier"
Mode                    = "min"  ### max, min
Monitor                 = "val_loss_epoch"   ## val_f1_tuned ,val_loss_epoch
filename                = '{epoch:02d}-{val_loss_epoch:.4f}_{val_f1_epoch:.4f}_Classifier'
save_top_k              = 1

[DATA]
output_path             = "./"
balancing_strategy      = "WeightedRandomSampler"  #same # WeightedRandomSampler , downsample_negatives, oversample_positives , weighted_loss
use_focal_loss          = false
Patch_Size              = [256, 256]
Input_Size              = [64, 64]
dataset_negatives_subsample = 1.0
Downscale_Factor	    = 1
Num_of_Classes          = 2
weights                 = [0.5, 0.5]
Dataframe               = '/projects/wispermed_rp18/mitosisDetect/Data/final_dataset/final_dataset.csv'
datasets 		        = ['MIDOG', 'MITOS_WSI_CMC', 'MITOS_WSI_CCMCT','TUPAC16']     #,  #,'MIDOG', 'MITOS_WSI_CMC', 'MITOS_WSI_CCMCT','TUPAC16'  #### 'ICPR2012'
species			        = ['Human', 'Canine']
DomainGen_study         = false
train_dataset           = "MIDOG"

#nrrd_path               = "/projects/wispermed_rp18/mitosisDetect/Data/nrrd/"
#masks_path 		        =  "/projects/wispermed_rp18/mitosisDetect/Data/New_masks_pathosam"  # "/projects/wispermed_rp18/mitosisDetect/OMG-Net-test/New_masks_pathosam/"
nrrd_path               = "/local/work/wispermed_rp18/nrrd/"
masks_path 		        =  "/local/work/wispermed_rp18/New_masks_pathosam/"  # "/projects/wispermed_rp18/mitosisDetect/OMG-Net-test/New_masks_pathosam/"

val_size                = 0.1
Image_Type		        = ".tiff"
filenames_test          = ["MIDOG_006","MIDOG_007","MIDOG_014","MIDOG_015","MIDOG_018","MIDOG_026",
			   "MIDOG_029","MIDOG_031","MIDOG_032","MIDOG_035","MIDOG_050","MIDOG_052",
			   "MIDOG_057","MIDOG_058","MIDOG_059","MIDOG_064","MIDOG_066","MIDOG_074",
			   "MIDOG_088","MIDOG_093","MIDOG_095","MIDOG_100","MIDOG_102","MIDOG_104",
			   "MIDOG_107","MIDOG_109","MIDOG_115","MIDOG_116","MIDOG_123","MIDOG_124",
			   "MIDOG_128","MIDOG_147","MIDOG_150","MIDOG_203","MIDOG_212","MIDOG_218",
			   "MIDOG_220","MIDOG_230","MIDOG_232","MIDOG_234","MIDOG_236","MIDOG_239",
			   "MIDOG_241","MIDOG_249","MIDOG_251","MIDOG_252","MIDOG_253","MIDOG_256",
			   "MIDOG_257","MIDOG_268","MIDOG_269","MIDOG_276","MIDOG_291","MIDOG_292",
		   	   "MIDOG_295","MIDOG_305","MIDOG_310","MIDOG_311","MIDOG_315","MIDOG_329",
			   "MIDOG_336","MIDOG_338","MIDOG_339","MIDOG_344","MIDOG_345","MIDOG_346",
			   "MIDOG_353","MIDOG_354","MIDOG_366","MIDOG_368","MIDOG_370","MIDOG_373",
			   "MIDOG_375","MIDOG_383","MIDOG_386","MIDOG_389","MIDOG_390","MIDOG_398",
			   "MIDOG_413","MIDOG_414","MIDOG_419","MIDOG_422","MIDOG_425","MIDOG_426",
			   "MIDOG_427","MIDOG_439","MIDOG_442","MIDOG_456","MIDOG_458","MIDOG_463",
			   "MIDOG_472","MIDOG_476","MIDOG_477","MIDOG_481","MIDOG_484","MIDOG_485",
			   "MIDOG_487","MIDOG_491","MIDOG_497","MIDOG_504","MIDOG_510","MIDOG_512",
			   "MIDOG_528","MIDOG_531","MIDOG_533","MIDOG_534","MIDOG_537","MIDOG_538",
			   "MIDOG_539","MIDOG_541","MIDOG_552"]


[OPTIMIZER]
Algorithm               = 'AdamW'
eps                     = 1e-7
lr                      = 5e-4

[REGULARIZATION]
Label_Smoothing         = 0.03
Stoch_Depth             = 0
Weight_Decay            = 1e-4
Momentum                = 0.9
 
[SCHEDULER]
Lin_Gamma               = 0.5
Lin_Step_Size           = 5
Type                    = "CosineAnnealingLR"
warmup_epochs           = 2
    







